### ISSUE TITLE
Time does not always accurately reset on re-run

### ISSUE THREAD

**Issue by philcockfield** [Respondly/meteor-test-reporter#20]
To recreate:

1. Run the tests (example I used was Util)
2. The time is calculated.
3. Reload the page.
4. The starting time will flash to a longer time (say 13s) before resetting to 0.

**Comment by rissem** [comment]
This one's proving a little tricky to track down.

The time is accurate for me 95% of the time. I do see the flash of a wrong number sometimes, but I haven't been able to spot a pattern yet.

Sometimes (also pretty rarely) the test suite doesn't actually finish running (aggregateComplete is false) and the elapsed time keeps increasing indefinitely.

If anyone gets a reliable reproduction of either of these it'd be very helpful.

**Comment by rissem** [comment]
Found a reliable reproduction of test suite not finishing. Performing a 'meteor' operation outside of a fiber will cause the test suite to not finish

```coffee
  it "throws an error outside of a fiber", (done)->
    setTimeout ->
      VelocityTestFiles.findOne()
      throw "Fiberless error"
    , 500
```

**Comment by rissem** [comment]
Nvm, not reliable. it's possible to enter a weird state when you open multiple tabs for the reporter.
