### ISSUE TITLE
Totals not calculating correctly

### ISSUE THREAD

**Issue by philcockfield** [Respondly/meteor-test-reporter#3]
From `rt test 22` - the Data package.

![screen shot 2014-12-18 at 9 56 42 am](https://cloud.githubusercontent.com/assets/185555/5478802/45e068c2-869c-11e4-886d-c716ec1a9c54.png)

**Comment by rissem** [comment]
Pretty sure this is caused by pending tests. Should we add a pending column? Or maybe just drop them from the total test count?

**Comment by timhaines** [comment]
Are pending tests tests that are still in the process of running, or tests that have been instructed not to run?

**Comment by rissem** [comment]
Pending tests are tests that haven't been filled out yet. When the developer thinks "this would be a good test to have, but i'm not going to do it right now"

**Comment by timhaines** [comment]
Lets add another column for now, and we can drop them later if the column seems pointless?

**Comment by rissem** [comment]
Works for me.

**Comment by rissem** [comment]
Just noticed that it.skip is not counted as well.

**Comment by rissem** [comment]
Ran across another issue adding sample tests for all the shared packages in the main app. If a test has identical group and test names, it is only counted once in the reporter. (This will not be unusual when testing multiple packages simultaneously)

**Comment by rissem** [comment]
Another way the counts can get off is when identical names are used for specs in the same suite.

**Comment by philcockfield** [comment]
Oh - is duplicate names happening?

**Comment by rissem** [comment]
It's happening in meteor-data (I'll push a fix soon). I think it's reasonable to log a warning if a name is repeated. Thoughts?
