### ISSUE TITLE
Travis.cl intergration

### ISSUE THREAD

**Issue by crenwick** [Respondly/meteor-test-reporter#34]
What is the current recommended strategy to test standalone meteor packages on travis-cl with mike:mocha-package?

I've been playing around with a few strategies, but so far nothing has worked.

Ideally I'd like to just add something this to my .travis.yml file:
```sh
script:
  - meteor test-packages --velocity --driver-package respondly:test-reporter -p 10015 ./
```
However its output stalls out:
```
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
grove:grove-api: updating npm dependencies -- spark...
=> Babel active on file extensions: es6.js, es6, jsx
=> Started your app.
=> App running at: http://localhost:10015/
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```
*Note: That script runs fine on my local machine.*

My alternative strategy was to use https://github.com/arunoda/travis-ci-meteor-packages. His script runs in browser tests in the dev console through phantomjs and report it back to travis. However, for it to work it runs `-driver-package test-in-console`, which conflicts with `-driver-package respondly:test-reporter` as there can only be one driver package running a test.

The https://www.npmjs.com/package/spacejam has the same issue.

Is there a method to run the `respondly:test-reporter` in the browser console? Or better yet, a fix for the first strategy?

Thanks so much. In general, this testing method is miles better than the mocha wraper/tinytest suite I was running before.

**Comment by zimme** [comment]
`meteor test-packages --velocity --driver-package velocity:console-reporter ./` might be an alternative?

**Comment by crenwick** [comment]
Yup. Got this working a few days ago with velocity:console-reporter. Thanks @zimme
