### ISSUE TITLE
CI reports success with failed tests with --velocity

### ISSUE THREAD

**Issue by chmac** [Respondly/meteor-test-reporter#37]
We're trying to run `mike:mocha-package` on CircleCI. Although it mostly fails to exit, see #36, it's now reporting success even with test failures.

If I run it without the `--velocity` flag, tests are accurately reported as failed in the web browser. However, with the `--velocity` flag, I see output like this:

```
PASSED mocha : foo:Bar => test name
[34mI20150602-14:08:56.838(0)? [39mexpected foo to have been called at least once, but it was never called
```
The assertion is failing, but the test is still passing. Not sure if this should be reported here or in [mad-eye/meteor-mocha-web](/mad-eye/meteor-mocha-web). Happy to post the issue there instead if it belongs there. I suspected the issue was in the test reporter because it correctly reports failure on the web interface.

**Comment by philcockfield** [comment]
Hi there Callum.  These mad-eye/meteor-mocha-web is a better place to post that.  This repo is just the visual reporter.  @rissem had experience getting this working on Circle CI too.
