### ISSUE TITLE
error calling testsComplete function { [Error: Match error: Expected string, got undefined]

### ISSUE THREAD

**Issue by dmitrijs-balcers** [Respondly/meteor-test-reporter#43]
After upgrading to `METEOR@1.2.0.2` I'm receiving the following error after running tests with this command: `meteor test-packages --driver-package respondly:test-reporter --port 3333`

I use this package to run tests: `mike:mocha-package@0.5.8`

Maybe you have any suggestions how can I resolve this issue and why it occurred?

**Comment by dmitrijs-balcers** [comment]
https://github.com/mad-eye/meteor-mocha-web/issues/194 This might be related

**Comment by marcodejongh** [comment]
:+1:

**Comment by rissem** [comment]
Should be resolved with mike:mocha-package@0.5.9

Let me know if you're still seeing anything, and sorry this took me so long for me to get to.
